// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eqsaqcviniucqomymvcg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxc2FxY3Zpbml1Y3FvbXltdmNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MDY5MzcsImV4cCI6MjA3NDM4MjkzN30.iQzo4jqbwGisczTSO7BqBR0raFYjCWsJSov4jKJlxs8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});